// GENERATED by tool/generate.dart — do not edit by hand.

import 'common/alig_rule.dart';
import 'rules/common/avoid_duplicate_cascades.dart';
import 'rules/common/avoid_duplicate_constant_values.dart';
import 'rules/common/avoid_duplicate_exports.dart';
import 'rules/common/avoid_duplicate_initializers.dart';
import 'rules/common/avoid_duplicate_map_keys.dart';
import 'rules/common/avoid_duplicate_mixins.dart';
import 'rules/common/avoid_duplicate_patterns.dart';
import 'rules/common/avoid_duplicate_switch_case_conditions.dart';
import 'rules/common/avoid_duplicate_test_assertions.dart';
import 'rules/flutter/avoid_empty_setstate.dart';
import 'rules/common/avoid_equal_expressions.dart';
import 'rules/common/avoid_passing_self_as_argument.dart';
import 'rules/common/avoid_redundant_else.dart';
import 'rules/common/avoid_redundant_pragma_inline.dart';
import 'rules/common/avoid_self_assignment.dart';
import 'rules/common/avoid_self_compare.dart';
import 'rules/common/avoid_unnecessary_call.dart';
import 'rules/common/avoid_unnecessary_compare_to.dart';
import 'rules/common/avoid_unnecessary_conditionals.dart';
import 'rules/common/avoid_unnecessary_continue.dart';
import 'rules/common/avoid_unnecessary_enum_arguments.dart';
import 'rules/common/avoid_unnecessary_extends.dart';
import 'rules/common/avoid_unnecessary_if.dart';
import 'rules/common/avoid_unnecessary_late_fields.dart';
import 'rules/common/avoid_unnecessary_local_late.dart';
import 'rules/common/avoid_unnecessary_local_variable.dart';
import 'rules/common/avoid_unnecessary_negations.dart';
import 'rules/common/avoid_unnecessary_overrides.dart';
import 'rules/common/avoid_unnecessary_reassignment.dart';
import 'rules/common/no_equal_conditions.dart';
import 'rules/common/no_equal_nested_conditions.dart';
import 'rules/common/no_equal_switch_case.dart';
import 'rules/common/no_equal_switch_expression_cases.dart';
import 'rules/common/no_equal_then_else.dart';

/// Every implemented rule in this package.
const List<AligRuleFactory> aligRuleFactories = [
  AvoidDuplicateCascades.new,
  AvoidDuplicateConstantValues.new,
  AvoidDuplicateExports.new,
  AvoidDuplicateInitializers.new,
  AvoidDuplicateMapKeys.new,
  AvoidDuplicateMixins.new,
  AvoidDuplicatePatterns.new,
  AvoidDuplicateSwitchCaseConditions.new,
  AvoidDuplicateTestAssertions.new,
  AvoidEmptySetstate.new,
  AvoidEqualExpressions.new,
  AvoidPassingSelfAsArgument.new,
  AvoidRedundantElse.new,
  AvoidRedundantPragmaInline.new,
  AvoidSelfAssignment.new,
  AvoidSelfCompare.new,
  AvoidUnnecessaryCall.new,
  AvoidUnnecessaryCompareTo.new,
  AvoidUnnecessaryConditionals.new,
  AvoidUnnecessaryContinue.new,
  AvoidUnnecessaryEnumArguments.new,
  AvoidUnnecessaryExtends.new,
  AvoidUnnecessaryIf.new,
  AvoidUnnecessaryLateFields.new,
  AvoidUnnecessaryLocalLate.new,
  AvoidUnnecessaryLocalVariable.new,
  AvoidUnnecessaryNegations.new,
  AvoidUnnecessaryOverrides.new,
  AvoidUnnecessaryReassignment.new,
  NoEqualConditions.new,
  NoEqualNestedConditions.new,
  NoEqualSwitchCase.new,
  NoEqualSwitchExpressionCases.new,
  NoEqualThenElse.new,
];
