// GENERATED by tool/generate.dart — do not edit by hand.

import 'common/alig_rule.dart';
import 'rules/common/avoid_accessing_collections_by_constant_index.dart';
import 'rules/common/avoid_always_null_parameters.dart';
import 'rules/common/avoid_assignments_as_conditions.dart';
import 'rules/common/avoid_cascade_after_if_null.dart';
import 'rules/common/avoid_casting_to_extension_type.dart';
import 'rules/common/avoid_collection_equality_checks.dart';
import 'rules/common/avoid_conditions_with_boolean_literals.dart';
import 'rules/common/avoid_constant_assert_conditions.dart';
import 'rules/common/avoid_constant_conditions.dart';
import 'rules/common/avoid_constant_switches.dart';
import 'rules/common/avoid_default_tostring.dart';
import 'rules/common/avoid_duplicate_cascades.dart';
import 'rules/common/avoid_duplicate_constant_values.dart';
import 'rules/common/avoid_duplicate_exports.dart';
import 'rules/common/avoid_duplicate_initializers.dart';
import 'rules/common/avoid_duplicate_map_keys.dart';
import 'rules/common/avoid_duplicate_mixins.dart';
import 'rules/common/avoid_duplicate_patterns.dart';
import 'rules/common/avoid_duplicate_switch_case_conditions.dart';
import 'rules/common/avoid_duplicate_test_assertions.dart';
import 'rules/common/avoid_dynamic.dart';
import 'rules/flutter/avoid_empty_setstate.dart';
import 'rules/common/avoid_empty_spread.dart';
import 'rules/common/avoid_enum_values_by_index.dart';
import 'rules/common/avoid_equal_expressions.dart';
import 'rules/common/avoid_explicit_pattern_field_name.dart';
import 'rules/common/avoid_keywords_in_wildcard_pattern.dart';
import 'rules/common/avoid_map_keys_contains.dart';
import 'rules/common/avoid_missing_enum_constant_in_map.dart';
import 'rules/common/avoid_misused_set_literals.dart';
import 'rules/common/avoid_multi_assignment.dart';
import 'rules/common/avoid_nested_shorthands.dart';
import 'rules/common/avoid_only_rethrow.dart';
import 'rules/common/avoid_passing_self_as_argument.dart';
import 'rules/common/avoid_redundant_else.dart';
import 'rules/common/avoid_redundant_positional_field_name.dart';
import 'rules/common/avoid_redundant_pragma_inline.dart';
import 'rules/common/avoid_self_assignment.dart';
import 'rules/common/avoid_self_compare.dart';
import 'rules/common/avoid_throw_in_catch_block.dart';
import 'rules/common/avoid_unconditional_break.dart';
import 'rules/common/avoid_unnecessary_call.dart';
import 'rules/common/avoid_unnecessary_collections.dart';
import 'rules/common/avoid_unnecessary_compare_to.dart';
import 'rules/common/avoid_unnecessary_conditionals.dart';
import 'rules/common/avoid_unnecessary_continue.dart';
import 'rules/common/avoid_unnecessary_enum_arguments.dart';
import 'rules/common/avoid_unnecessary_extends.dart';
import 'rules/common/avoid_unnecessary_if.dart';
import 'rules/common/avoid_unnecessary_late_fields.dart';
import 'rules/common/avoid_unnecessary_local_late.dart';
import 'rules/common/avoid_unnecessary_local_variable.dart';
import 'rules/common/avoid_unnecessary_negations.dart';
import 'rules/common/avoid_unnecessary_overrides.dart';
import 'rules/common/avoid_unnecessary_reassignment.dart';
import 'rules/common/avoid_unnecessary_return.dart';
import 'rules/common/avoid_unnecessary_statements.dart';
import 'rules/common/avoid_unnecessary_super.dart';
import 'rules/common/avoid_unreachable_for_loop.dart';
import 'rules/common/avoid_unsafe_collection_methods.dart';
import 'rules/common/avoid_wildcard_cases_with_enums.dart';
import 'rules/common/avoid_wildcard_cases_with_sealed_classes.dart';
import 'rules/common/function_always_returns_null.dart';
import 'rules/common/function_always_returns_same_value.dart';
import 'rules/common/no_empty_block.dart';
import 'rules/common/no_equal_conditions.dart';
import 'rules/common/no_equal_nested_conditions.dart';
import 'rules/common/no_equal_switch_case.dart';
import 'rules/common/no_equal_switch_expression_cases.dart';
import 'rules/common/no_equal_then_else.dart';
import 'rules/common/prefer_any_or_every.dart';
import 'rules/common/prefer_correct_for_loop_increment.dart';
import 'rules/common/prefer_iterable_of.dart';
import 'rules/common/prefer_null_aware_elements.dart';
import 'rules/common/prefer_null_aware_spread.dart';
import 'rules/common/prefer_parentheses_with_if_null.dart';
import 'rules/common/prefer_returning_shorthands.dart';
import 'rules/common/prefer_shorthands_with_enums.dart';
import 'rules/common/prefer_shorthands_with_static_fields.dart';
import 'rules/common/prefer_simpler_boolean_expressions.dart';
import 'rules/common/prefer_simpler_patterns_null_check.dart';
import 'rules/common/prefer_switch_with_enums.dart';
import 'rules/common/prefer_wildcard_pattern.dart';

/// Every implemented rule in this package.
const List<AligRuleFactory> aligRuleFactories = [
  AvoidAccessingCollectionsByConstantIndex.new,
  AvoidAlwaysNullParameters.new,
  AvoidAssignmentsAsConditions.new,
  AvoidCascadeAfterIfNull.new,
  AvoidCastingToExtensionType.new,
  AvoidCollectionEqualityChecks.new,
  AvoidConditionsWithBooleanLiterals.new,
  AvoidConstantAssertConditions.new,
  AvoidConstantConditions.new,
  AvoidConstantSwitches.new,
  AvoidDefaultTostring.new,
  AvoidDuplicateCascades.new,
  AvoidDuplicateConstantValues.new,
  AvoidDuplicateExports.new,
  AvoidDuplicateInitializers.new,
  AvoidDuplicateMapKeys.new,
  AvoidDuplicateMixins.new,
  AvoidDuplicatePatterns.new,
  AvoidDuplicateSwitchCaseConditions.new,
  AvoidDuplicateTestAssertions.new,
  AvoidDynamic.new,
  AvoidEmptySetstate.new,
  AvoidEmptySpread.new,
  AvoidEnumValuesByIndex.new,
  AvoidEqualExpressions.new,
  AvoidExplicitPatternFieldName.new,
  AvoidKeywordsInWildcardPattern.new,
  AvoidMapKeysContains.new,
  AvoidMissingEnumConstantInMap.new,
  AvoidMisusedSetLiterals.new,
  AvoidMultiAssignment.new,
  AvoidNestedShorthands.new,
  AvoidOnlyRethrow.new,
  AvoidPassingSelfAsArgument.new,
  AvoidRedundantElse.new,
  AvoidRedundantPositionalFieldName.new,
  AvoidRedundantPragmaInline.new,
  AvoidSelfAssignment.new,
  AvoidSelfCompare.new,
  AvoidThrowInCatchBlock.new,
  AvoidUnconditionalBreak.new,
  AvoidUnnecessaryCall.new,
  AvoidUnnecessaryCollections.new,
  AvoidUnnecessaryCompareTo.new,
  AvoidUnnecessaryConditionals.new,
  AvoidUnnecessaryContinue.new,
  AvoidUnnecessaryEnumArguments.new,
  AvoidUnnecessaryExtends.new,
  AvoidUnnecessaryIf.new,
  AvoidUnnecessaryLateFields.new,
  AvoidUnnecessaryLocalLate.new,
  AvoidUnnecessaryLocalVariable.new,
  AvoidUnnecessaryNegations.new,
  AvoidUnnecessaryOverrides.new,
  AvoidUnnecessaryReassignment.new,
  AvoidUnnecessaryReturn.new,
  AvoidUnnecessaryStatements.new,
  AvoidUnnecessarySuper.new,
  AvoidUnreachableForLoop.new,
  AvoidUnsafeCollectionMethods.new,
  AvoidWildcardCasesWithEnums.new,
  AvoidWildcardCasesWithSealedClasses.new,
  FunctionAlwaysReturnsNull.new,
  FunctionAlwaysReturnsSameValue.new,
  NoEmptyBlock.new,
  NoEqualConditions.new,
  NoEqualNestedConditions.new,
  NoEqualSwitchCase.new,
  NoEqualSwitchExpressionCases.new,
  NoEqualThenElse.new,
  PreferAnyOrEvery.new,
  PreferCorrectForLoopIncrement.new,
  PreferIterableOf.new,
  PreferNullAwareElements.new,
  PreferNullAwareSpread.new,
  PreferParenthesesWithIfNull.new,
  PreferReturningShorthands.new,
  PreferShorthandsWithEnums.new,
  PreferShorthandsWithStaticFields.new,
  PreferSimplerBooleanExpressions.new,
  PreferSimplerPatternsNullCheck.new,
  PreferSwitchWithEnums.new,
  PreferWildcardPattern.new,
];
