import 'dart:io';

import 'src/manifest.dart';

/// Regenerates every derived file from `tool/rules_manifest.json`.
///
/// Run from the package root: `dart run tool/generate.dart`
void main() {
  final manifest = Manifest.load();
  final implemented = manifest.done;

  _writeRegistry(implemented);
  _writePresets(implemented);
  _updateReadmeProgress(manifest);

  stdout.writeln(
    'Generated registry and presets for ${implemented.length}/'
    '${manifest.rules.length} rules.',
  );
}

void _writeRegistry(List<RuleEntry> rules) {
  final sorted = [...rules]..sort((a, b) => a.name.compareTo(b.name));
  final imports = [
    for (final rule in sorted)
      "import 'rules/${rule.category}/${rule.fileName}.dart';",
  ];
  final entries = [for (final rule in sorted) '  ${rule.className}.new,'];

  File('lib/src/registry.dart').writeAsStringSync('''
// GENERATED by tool/generate.dart — do not edit by hand.

import 'common/alig_rule.dart';
${imports.join('\n')}

/// Every implemented rule in this package.
const List<AligRuleFactory> aligRuleFactories = [
${entries.join('\n')}
];
''');
}

void _writePresets(List<RuleEntry> rules) {
  File('lib/all.yaml').writeAsStringSync(_preset(rules));
  File('lib/flutter.yaml').writeAsStringSync(
    _preset(rules.where((r) => r.category == 'flutter').toList()),
  );
  File('lib/recommended.yaml').writeAsStringSync(
    _preset(rules.where((r) => r.severity == 'warning').toList()),
  );
}

/// Builds a consumer-facing analysis_options preset.
String _preset(List<RuleEntry> rules) {
  final names = [for (final rule in rules) '    - ${rule.name}']..sort();

  return '''
# GENERATED by tool/generate.dart — do not edit by hand.
include: package:alig_lints/dart_lints.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  enable_all_lint_rules: false
  rules:
${names.isEmpty ? '    []' : names.join('\n')}
''';
}

void _updateReadmeProgress(Manifest manifest) {
  final readme = File('README.md');
  if (!readme.existsSync()) return;

  final byPhase = <int, List<RuleEntry>>{};
  for (final rule in manifest.rules) {
    byPhase.putIfAbsent(rule.phase, () => []).add(rule);
  }

  const themes = {
    1: 'Structural equality',
    2: 'Unnecessary and redundant code',
    3: 'Conditions, control flow, patterns',
    4: 'Collections and Iterable members',
    5: 'Nullability, toString, casts',
    6: 'Async and futures',
    7: 'Flutter widgets and life cycle',
    8: 'Disposal and memory leaks',
    9: 'Unused code, naming, style',
  };

  final rows = [
    for (final phase in byPhase.keys.toList()..sort())
      '| ${themes[phase] ?? phase} | '
          '${byPhase[phase]!.where((r) => r.isSettled).length} / '
          '${byPhase[phase]!.length} |',
  ];
  final needsSpec = manifest.rules.where((r) => r.needsSpec).length;
  final covered = manifest.covered.length;
  final notes = [
    if (needsSpec > 0) '$needsSpec awaiting clarification',
    if (covered > 0) '$covered covered elsewhere',
  ];
  final suffix = notes.isEmpty ? '' : ' — ${notes.join(', ')}';

  final table = '''
<!-- progress:start -->
**${manifest.done.length} / ${manifest.rules.length} rules implemented**$suffix

| Theme | Settled |
|---|---|
${rows.join('\n')}
<!-- progress:end -->''';

  final updated = readme.readAsStringSync().replaceFirst(
        RegExp(r'<!-- progress:start -->[\s\S]*<!-- progress:end -->'),
        table,
      );
  readme.writeAsStringSync(updated);
}
